#- name: Create_standbyDB | Prep for creating  a Physical Standby Database
#  include: dg_prep_psb.yml
#  tags: pre_tasks_creaphysb
#
#- name: Create_standbyDB | Create a Physical Standby Database
#  when: inventory_hostname in groups['ora-x2'] 
#  remote_user: "{{ root_user }}"
#  become: yes
#  become_user: "{{ oracle_user }}"
#  shell: "{{ stage_dir }}/sbdbcreate.sh"
#  tags:
#   - db19c_sbcrepsb
#
#- name: display post install message after creating of Physical Standby
#  when: inventory_hostname in groups['ora-x1']
#  debug:
#    msg:
#      - 'This Steps completed below task for Single Instance at {{ansible_date_time.iso8601}}:'
#      - '- Create a Physical Standby Database is completed on server ora-x2'
#      - '- Next we need to setup Data Guard Broker configuration'
#
#- name: Create_standbyDB | Setup Data Guard broker configuration
#  include: dg_brokersetup.yml
#  tags: dgbroker_setup

- name: validate DG Configuration
  include: tasks/dg_validate.yml
  tags: dgbroker_status
